param(
    [string]$Title = "feat: moderniser interface Tabler",
    [string]$Body = @"
## Résumé
- refonte des pages Tabler (employees/index/periods) connectées aux KPI recalculés
- alignement providers/services/migrations/tests pour supporter les métriques multi-périodes

## Tests
- isort
- black
- ruff format & check
- mypy ciblé
- pytest
- bandit (limitations Python 3.14 → nombreux fichiers ignorés automatiquement)
- safety
- scripts/forbid_direct_db_connect
"@
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

function Require-Cmd {
    param([string]$Command)
    if (-not (Get-Command $Command -ErrorAction SilentlyContinue)) {
        throw "Commande requise manquante: $Command"
    }
}

Require-Cmd git
Require-Cmd gh

$branch = (git rev-parse --abbrev-ref HEAD).Trim()
if (-not $branch) {
    throw "Impossible de déterminer la branche courante."
}

Write-Host ">>> Branche détectée : $branch"

Write-Host ">>> Synchronisation et push…"
git push --set-upstream origin $branch

Write-Host ">>> Création de la Pull Request (draft)…"
$bodyFile = $null
try {
    $bodyFile = [System.IO.Path]::GetTempFileName()
    Set-Content -Path $bodyFile -Value $Body -Encoding UTF8

    $ghArgs = @(
        "pr", "create",
        "--title", $Title,
        "--body-file", $bodyFile,
        "--draft",
        "--label", "autogenerated"
    )

    $prProcess = Start-Process -FilePath "gh" -ArgumentList $ghArgs -NoNewWindow -Wait -PassThru -RedirectStandardOutput TempPR.out -RedirectStandardError TempPR.err
    $prStdOut = Get-Content TempPR.out
    $prStdErr = Get-Content TempPR.err
    Remove-Item TempPR.out, TempPR.err -ErrorAction SilentlyContinue
}
finally {
    if (Test-Path $bodyFile) {
        Remove-Item $bodyFile -ErrorAction SilentlyContinue
    }
}

if ($prProcess.ExitCode -ne 0) {
    Write-Host $prStdOut
    Write-Error ("La création de la PR a échoué (code {0}). Détails :`n{1}" -f $prProcess.ExitCode, ($prStdErr -join [Environment]::NewLine))
    exit $prProcess.ExitCode
}

Write-Host $prStdOut
Write-Host ">>> PR créée (draft)."

