param(
    [string]$Title = "feat: moderniser interface Tabler",
    [string]$Body = @"
## Résumé
- refonte des pages Tabler (employees/index/periods) connectées aux KPI recalculés
- alignement providers/services/migrations/tests pour supporter les métriques multi-périodes

## Tests
- isort
- black
- ruff format & check
- mypy ciblé
- pytest
- bandit (limitations Python 3.14 → nombreux fichiers ignorés automatiquement)
- safety
- scripts/forbid_direct_db_connect
"@
)

$labelName = "autogenerated"

function Ensure-Label {
    param([string]$Name)
    $labelsRaw = & gh label list --limit 200 --json name
    $labels = @()
    if ($labelsRaw) {
        $labels = $labelsRaw | ConvertFrom-Json
    }
    $exists = $labels | Where-Object { $_.name -eq $Name }
    if (-not $exists) {
        & gh label create $Name --color BFDADC --description "PR créée automatiquement" *> $null
    }
}

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

function Require-Cmd {
    param([string]$Command)
    if (-not (Get-Command $Command -ErrorAction SilentlyContinue)) {
        throw "Commande requise manquante: $Command"
    }
}

Require-Cmd git
Require-Cmd gh
Ensure-Label -Name $labelName

$branch = (git rev-parse --abbrev-ref HEAD).Trim()
if (-not $branch) {
    throw "Impossible de déterminer la branche courante."
}

Write-Host ">>> Branche détectée : $branch"

Write-Host ">>> Synchronisation et push…"
git push --set-upstream origin $branch

Write-Host ">>> Création de la Pull Request (draft)…"
$bodyFile = $null
try {
    $bodyFile = [System.IO.Path]::GetTempFileName()
    Set-Content -Path $bodyFile -Value $Body -Encoding UTF8

    $ghArgs = @(
        "pr", "create",
        "--title", $Title,
        "--body-file", $bodyFile,
        "--draft",
        "--label", $labelName
    )

$prStdOut = & gh @ghArgs 2>&1
$prExit = $LASTEXITCODE
}
finally {
    if (Test-Path $bodyFile) {
        Remove-Item $bodyFile -ErrorAction SilentlyContinue
    }
}

if ($prExit -ne 0) {
    Write-Error ("La création de la PR a échoué (code {0}). Détails :`n{1}" -f $prExit, ($prStdOut -join [Environment]::NewLine))
    exit $prExit
}

Write-Host ($prStdOut -join [Environment]::NewLine)
Write-Host ">>> PR créée (draft)."

